// tools/recorder/build.mjs
// Produces dist/doc-agent.mjs: a READABLE bundle (no minify) to run on the portable Node.
// Also regenerates THIRD-PARTY-NOTICES.md at the repo root: the bundle redistributes
// compiled copies of the packages below, whose licenses require the notices to ship along.
import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';

const BUNDLED_PACKAGES = ['playwright-core', 'marked', 'pngjs'];

function thirdPartyNotices() {
  const sections = BUNDLED_PACKAGES.map((pkg) => {
    const dir = path.join('node_modules', pkg);
    const meta = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const licenseName = fs.readdirSync(dir).find((f) => /^LICENSE(\.(md|txt))?$/i.test(f));
    if (!licenseName) throw new Error(`no LICENSE file found for ${pkg}`);
    const repo = typeof meta.repository === 'string' ? meta.repository : (meta.repository?.url ?? '');
    const source = repo.replace(/^git\+/, '').replace(/^git:\/\//, 'https://').replace(/\.git$/, '');
    return [
      `## ${meta.name} ${meta.version}`,
      '',
      `- License: ${meta.license}`,
      `- Source: ${source}`,
      '',
      '```',
      // Some packages ship their LICENSE with CRLF (playwright-core does);
      // normalize so the generated file is byte-identical on every platform.
      fs.readFileSync(path.join(dir, licenseName), 'utf8').replace(/\r\n/g, '\n').trim(),
      '```',
    ].join('\n');
  });
  return [
    '# Third-Party Notices',
    '',
    '<!-- Generated by tools/recorder/build.mjs — do not edit by hand. -->',
    '',
    'The committed bundle `dist/doc-agent.mjs` contains compiled copies of the open-source',
    'packages below. Their license texts are reproduced in full, as required for',
    'redistribution. The doc-agent source code itself is licensed under [MIT](LICENSE).',
    '',
    sections.join('\n\n---\n\n'),
    '',
  ].join('\n');
}

// playwright-core references 'electron' on a path we never take (we only use connectOverCDP).
// An empty stub avoids a resolution error in the bundle.
const stubs = {
  name: 'stubs',
  setup(build) {
    build.onResolve({ filter: /^electron(\/|$)/ }, (args) => ({ path: args.path, namespace: 'stub' }));
    // chromium-bidi: optional playwright-core dependency for the BiDi protocol (Firefox); we only use CDP.
    build.onResolve({ filter: /^chromium-bidi(\/|$)/ }, (args) => ({ path: args.path, namespace: 'stub' }));
    build.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: 'module.exports = {};' }));
  },
};

// playwright-core reads these two JSON files at RUNTIME via require(path computed from
// __dirname) — no build-time stub handles that. We inline their contents (~3 KB) in the
// banner and intercept require so the bundle is fully self-contained (runs from any
// folder, with no node_modules).
const pwPackageJSON = fs.readFileSync('node_modules/playwright-core/package.json', 'utf8');
const pwBrowsersJSON = fs.readFileSync('node_modules/playwright-core/browsers.json', 'utf8');

await esbuild.build({
  entryPoints: ['src/cli.js'],
  outfile: '../../dist/doc-agent.mjs',
  bundle: true,
  minify: false,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  plugins: [stubs],
  banner: {
    js: [
      '// doc-agent — bundle produced by tools/recorder/build.mjs (esbuild, NOT minified).',
      '// The canonical source lives in tools/recorder/src/. This file exists so the tool',
      '// runs without npm install: runtime\\node.exe dist\\doc-agent.mjs <command>',
      "import { createRequire as __createRequire } from 'node:module';",
      "import { fileURLToPath as __fileURLToPath } from 'node:url';",
      "import __path from 'node:path';",
      '// __dirname/__filename: the playwright-core CJS code converted to ESM references both.',
      'const __filename = __fileURLToPath(import.meta.url);',
      'const __dirname = __path.dirname(__filename);',
      '// playwright-core package.json and browsers.json, inlined at build time (see the comment in build.mjs).',
      `const __pwPackageJSON = ${JSON.stringify(JSON.parse(pwPackageJSON))};`,
      `const __pwBrowsersJSON = ${JSON.stringify(JSON.parse(pwBrowsersJSON))};`,
      'const __rawRequire = __createRequire(import.meta.url);',
      "const __pwPackageRoot = __path.join(__dirname, '..'); // packageRoot computed by playwright-core at runtime",
      'const require = Object.assign((id) => {',
      "  if (id === __path.join(__pwPackageRoot, 'package.json')) return __pwPackageJSON;",
      "  if (id === __path.join(__pwPackageRoot, 'browsers.json')) return __pwBrowsersJSON;",
      '  return __rawRequire(id);',
      '}, __rawRequire);',
    ].join('\n'),
  },
});
console.log('bundle written: dist/doc-agent.mjs');

fs.writeFileSync('../../THIRD-PARTY-NOTICES.md', thirdPartyNotices());
console.log('notices written: THIRD-PARTY-NOTICES.md');
